//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketSoru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnketSoru()
        {
            this.AnketCevap = new HashSet<AnketCevap>();
        }
    
        public int AnketSoruId { get; set; }
        public int AnketId { get; set; }
        public string Soru { get; set; }
        public int Sira { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Anket Anket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevap> AnketCevap { get; set; }
    }
}
