//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketCevap
    {
        public int AnketCevapId { get; set; }
        public int AnketSoruId { get; set; }
        public System.Guid KullaniciId { get; set; }
        public bool CevapSonuc { get; set; }
        public System.DateTime Tarih { get; set; }
    
        public virtual AnketSoru AnketSoru { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
