//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int BannerId { get; set; }
        public int BannerTipId { get; set; }
        public string Adi { get; set; }
        public string Aciklama1 { get; set; }
        public string Aciklama2 { get; set; }
        public string Link { get; set; }
        public string Resim { get; set; }
        public int Sira { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual BannerTip BannerTip { get; set; }
    }
}
