//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banka> Banka { get; set; }
        public virtual DbSet<HesapNumarasi> HesapNumarasi { get; set; }
        public virtual DbSet<KrediKartiTip> KrediKartiTip { get; set; }
        public virtual DbSet<SanalPos> SanalPos { get; set; }
        public virtual DbSet<Taksit> Taksit { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Cache> Cache { get; set; }
        public virtual DbSet<EpostaKuyrugu> EpostaKuyrugu { get; set; }
        public virtual DbSet<IcerikAyar> IcerikAyar { get; set; }
        public virtual DbSet<IpAdres> IpAdres { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<SmsKuyrugu> SmsKuyrugu { get; set; }
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<AdresIl> AdresIl { get; set; }
        public virtual DbSet<AdresIlce> AdresIlce { get; set; }
        public virtual DbSet<FaturaTip> FaturaTip { get; set; }
        public virtual DbSet<Gonderim> Gonderim { get; set; }
        public virtual DbSet<IadeTalep> IadeTalep { get; set; }
        public virtual DbSet<IadeTalepDurumTip> IadeTalepDurumTip { get; set; }
        public virtual DbSet<IadeTalepIstekTip> IadeTalepIstekTip { get; set; }
        public virtual DbSet<IadeTalepNedenTip> IadeTalepNedenTip { get; set; }
        public virtual DbSet<Iskonto> Iskonto { get; set; }
        public virtual DbSet<IskontoKategori> IskontoKategori { get; set; }
        public virtual DbSet<IskontoKullanimHareket> IskontoKullanimHareket { get; set; }
        public virtual DbSet<IskontoMarka> IskontoMarka { get; set; }
        public virtual DbSet<IskontoRol> IskontoRol { get; set; }
        public virtual DbSet<IskontoSirket> IskontoSirket { get; set; }
        public virtual DbSet<IskontoTip> IskontoTip { get; set; }
        public virtual DbSet<IskontoUrun> IskontoUrun { get; set; }
        public virtual DbSet<IstekListesi> IstekListesi { get; set; }
        public virtual DbSet<KatmanliFiyat> KatmanliFiyat { get; set; }
        public virtual DbSet<KomisyonIskontoTip> KomisyonIskontoTip { get; set; }
        public virtual DbSet<OdemeDurumTip> OdemeDurumTip { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<SepetTip> SepetTip { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetay { get; set; }
        public virtual DbSet<SiparisDurumTip> SiparisDurumTip { get; set; }
        public virtual DbSet<SiparisGonderim> SiparisGonderim { get; set; }
        public virtual DbSet<SiparisHareket> SiparisHareket { get; set; }
        public virtual DbSet<SiparisOdemeTip> SiparisOdemeTip { get; set; }
        public virtual DbSet<TeslimZamani> TeslimZamani { get; set; }
        public virtual DbSet<Anket> Anket { get; set; }
        public virtual DbSet<AnketCevap> AnketCevap { get; set; }
        public virtual DbSet<AnketSoru> AnketSoru { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<BannerTip> BannerTip { get; set; }
        public virtual DbSet<HaberBlog> HaberBlog { get; set; }
        public virtual DbSet<HaberBlogResim> HaberBlogResim { get; set; }
        public virtual DbSet<HaberBlogTip> HaberBlogTip { get; set; }
        public virtual DbSet<HaberBlogYorum> HaberBlogYorum { get; set; }
        public virtual DbSet<HaberBulteniAbonelik> HaberBulteniAbonelik { get; set; }
        public virtual DbSet<Kampanya> Kampanya { get; set; }
        public virtual DbSet<KampanyaResim> KampanyaResim { get; set; }
        public virtual DbSet<KisaLink> KisaLink { get; set; }
        public virtual DbSet<SSS> SSS { get; set; }
        public virtual DbSet<IlgiliUrun> IlgiliUrun { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<KategoriOzellik> KategoriOzellik { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<Nitelik> Nitelik { get; set; }
        public virtual DbSet<NitelikGrup> NitelikGrup { get; set; }
        public virtual DbSet<Olcu> Olcu { get; set; }
        public virtual DbSet<OlcuTip> OlcuTip { get; set; }
        public virtual DbSet<Ozellik> Ozellik { get; set; }
        public virtual DbSet<OzellikTip> OzellikTip { get; set; }
        public virtual DbSet<Paket> Paket { get; set; }
        public virtual DbSet<PaketKategori> PaketKategori { get; set; }
        public virtual DbSet<PaketNitelik> PaketNitelik { get; set; }
        public virtual DbSet<PaketResim> PaketResim { get; set; }
        public virtual DbSet<PaketUrun> PaketUrun { get; set; }
        public virtual DbSet<StokHareket> StokHareket { get; set; }
        public virtual DbSet<StokHareketTip> StokHareketTip { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<UrunKategori> UrunKategori { get; set; }
        public virtual DbSet<UrunNitelik> UrunNitelik { get; set; }
        public virtual DbSet<UrunOzellik> UrunOzellik { get; set; }
        public virtual DbSet<UrunResim> UrunResim { get; set; }
        public virtual DbSet<UrunResimTip> UrunResimTip { get; set; }
        public virtual DbSet<UrunYorum> UrunYorum { get; set; }
        public virtual DbSet<Vergi> Vergi { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciAdres> KullaniciAdres { get; set; }
        public virtual DbSet<KullaniciDetay> KullaniciDetay { get; set; }
        public virtual DbSet<KullaniciRol> KullaniciRol { get; set; }
        public virtual DbSet<KullaniciYetki> KullaniciYetki { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sirket> Sirket { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
    }
}
