//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarantiPos
    {
        public int GarantiPosId { get; set; }
        public string Mode { get; set; }
        public string Version { get; set; }
        public string TerminalId { get; set; }
        public string ProvUserId { get; set; }
        public string ProvisionPassword { get; set; }
        public string UserId { get; set; }
        public string MerchantId { get; set; }
    }
}
