//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gonderim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gonderim()
        {
            this.SiparisGonderim = new HashSet<SiparisGonderim>();
        }
    
        public int GonderimId { get; set; }
        public string Adi { get; set; }
        public string Aciklama { get; set; }
        public string GonderimSorgulamaLink { get; set; }
        public decimal AltLimit { get; set; }
        public decimal Fiyat { get; set; }
        public string Resim { get; set; }
        public int Sira { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisGonderim> SiparisGonderim { get; set; }
    }
}
