//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaberYorum
    {
        public int HaberYorumId { get; set; }
        public int HaberId { get; set; }
        public string Yorum { get; set; }
        public int KullaniciId { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Haber Haber { get; set; }
    }
}
