//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaberBlogResim
    {
        public int ResimId { get; set; }
        public int HaberBlogId { get; set; }
        public string ResimYolu { get; set; }
        public string Aciklama { get; set; }
        public string AltAttribute { get; set; }
        public string TitleAttribute { get; set; }
        public bool YeniMi { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool AktifMi { get; set; }
    }
}
