//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IadeTalep
    {
        public int IadeTalepId { get; set; }
        public int SiparisDetayId { get; set; }
        public int IadeTalepNedenTipId { get; set; }
        public int IadeTalepIstekTipId { get; set; }
        public int IadeTalepDurumTipId { get; set; }
        public int Adet { get; set; }
        public string IadeNeden { get; set; }
        public string IadeIstek { get; set; }
        public string KullaniciAciklama { get; set; }
        public string PersonelAciklama { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public System.DateTime GuncellemeTarihi { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual IadeTalepDurumTip IadeTalepDurumTip { get; set; }
        public virtual IadeTalepIstekTip IadeTalepIstekTip { get; set; }
        public virtual IadeTalepNedenTip IadeTalepNedenTip { get; set; }
        public virtual SiparisDetay SiparisDetay { get; set; }
    }
}
