//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IcerikAyar
    {
        public int AyarId { get; set; }
        public string UygulamaAd { get; set; }
        public string UygulamaAciklama { get; set; }
        public string Url { get; set; }
        public string SecureUrl { get; set; }
        public string FacebookHesapUrl { get; set; }
        public string TwitterHesapUrl { get; set; }
        public int KeepAliveTime { get; set; }
        public int ClearCacheTime { get; set; }
        public int CookieTime { get; set; }
        public bool SslAktifMi { get; set; }
        public string SirketAd { get; set; }
        public string SirketAciklama { get; set; }
        public string SirketAdres { get; set; }
        public string SirketTelefon1 { get; set; }
        public string SirketTelefon2 { get; set; }
        public string SirketFax1 { get; set; }
        public string SirketFax2 { get; set; }
        public string SirketEposta { get; set; }
        public string SirketMapCode { get; set; }
        public string SirketHakkimizda { get; set; }
        public decimal ParaPuanLimit { get; set; }
        public decimal ParaPuanKazanc { get; set; }
        public bool ParaPuanAktifMi { get; set; }
        public bool SayfaUrunYorumAktifMi { get; set; }
        public bool SayfaKuponAktifMi { get; set; }
        public bool MisafirSatinAlmaAktifMi { get; set; }
        public bool KdvDahilMi { get; set; }
        public bool CacheAktifMi { get; set; }
        public bool IpBloklamaAktifMi { get; set; }
        public bool UygulamaAktifMi { get; set; }
        public string KucukLogoResimUrl { get; set; }
        public string BuyukLogoResimUrl { get; set; }
        public string GonderilecekEposta { get; set; }
        public string GonderilecekEpostaTanim { get; set; }
        public string GonderilecekEpostaKullaniciAdi { get; set; }
        public string GonderilecekEpostaSifre { get; set; }
        public string GonderilecekEpostaHost { get; set; }
        public int GonderilecekEpostaPort { get; set; }
        public bool GonderilecekEpostaAktifMi { get; set; }
        public string SmsKullaniciAdi { get; set; }
        public string SmsSifre { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MesafeliSatisSozlesmesi { get; set; }
        public string GuvenlikIlkeleri { get; set; }
        public string TuketiciHaklari { get; set; }
        public string IadeKosullari { get; set; }
        public string DDDSuccessURL { get; set; }
        public string DDDErrorURL { get; set; }
        public string DDDConfirmURL { get; set; }
    }
}
