//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iskonto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Iskonto()
        {
            this.IskontoKategori = new HashSet<IskontoKategori>();
            this.IskontoKullanimHareket = new HashSet<IskontoKullanimHareket>();
            this.IskontoUrun = new HashSet<IskontoUrun>();
            this.IskontoMarka = new HashSet<IskontoMarka>();
            this.IskontoRol = new HashSet<IskontoRol>();
            this.IskontoSirket = new HashSet<IskontoSirket>();
        }
    
        public int IskontoId { get; set; }
        public int IskontoTipId { get; set; }
        public string Adi { get; set; }
        public string Aciklama { get; set; }
        public decimal IskontoMiktari { get; set; }
        public Nullable<decimal> MinimumFiyat { get; set; }
        public Nullable<decimal> MaksimumFiyat { get; set; }
        public bool HediyeKartAktifMi { get; set; }
        public string HediyeKartKuponKod { get; set; }
        public Nullable<System.DateTime> BaslangicTarih { get; set; }
        public Nullable<System.DateTime> BitisTarih { get; set; }
        public int Sira { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IskontoKategori> IskontoKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IskontoKullanimHareket> IskontoKullanimHareket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IskontoUrun> IskontoUrun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IskontoMarka> IskontoMarka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IskontoRol> IskontoRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IskontoSirket> IskontoSirket { get; set; }
    }
}
