//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisaLink
    {
        public int KisaLinkId { get; set; }
        public string UzunLink { get; set; }
        public string KisaltilmisLink { get; set; }
        public int ZiyaretSayisi { get; set; }
        public bool AktifMi { get; set; }
    }
}
