//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciDetay
    {
        public System.Guid KullaniciDetayId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public byte[] KullaniciResim { get; set; }
        public Nullable<int> SirketId { get; set; }
        public bool SepetteUrunVarMi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Sirket Sirket { get; set; }
    }
}
