//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paket()
        {
            this.PaketKategori = new HashSet<PaketKategori>();
            this.PaketNitelik = new HashSet<PaketNitelik>();
            this.PaketResim = new HashSet<PaketResim>();
            this.PaketUrun = new HashSet<PaketUrun>();
        }
    
        public int PaketId { get; set; }
        public int VergiId { get; set; }
        public int NitelikGrupId { get; set; }
        public string PaketKod { get; set; }
        public string Adi { get; set; }
        public string KisaAciklama { get; set; }
        public string UzunAciklama { get; set; }
        public string Tags { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTitle { get; set; }
        public string OrnekDosyaYolu { get; set; }
        public bool SatinAlAktifMi { get; set; }
        public bool OnSiparisAktifMi { get; set; }
        public bool YeniMi { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public System.DateTime GuncellemeTarihi { get; set; }
        public int Sira { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual NitelikGrup NitelikGrup { get; set; }
        public virtual Vergi Vergi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaketKategori> PaketKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaketNitelik> PaketNitelik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaketResim> PaketResim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaketUrun> PaketUrun { get; set; }
    }
}
