//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiparisDetay()
        {
            this.IadeTalep = new HashSet<IadeTalep>();
            this.SiparisGonderim = new HashSet<SiparisGonderim>();
        }
    
        public int SiparisDetayId { get; set; }
        public int SiparisId { get; set; }
        public int UrunId { get; set; }
        public int Adet { get; set; }
        public decimal UrunBirimKdvDahilTutar { get; set; }
        public decimal UrunBirimKdvHaricTutar { get; set; }
        public decimal UrunBirimKdvTutar { get; set; }
        public decimal HesaplananBirimKdvDahilTutar { get; set; }
        public decimal HesaplananBirimKdvHaricTutar { get; set; }
        public decimal HesaplananBirimKdvTutar { get; set; }
        public decimal HesaplananKdvDahilTutar { get; set; }
        public decimal HesaplananKdvHaricTutar { get; set; }
        public decimal HesaplananKdvTutar { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IadeTalep> IadeTalep { get; set; }
        public virtual Siparis Siparis { get; set; }
        public virtual Urun Urun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisGonderim> SiparisGonderim { get; set; }
    }
}
