//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisGonderim
    {
        public int SiparisGonderimId { get; set; }
        public int SiparisDetayId { get; set; }
        public int GonderimId { get; set; }
        public int TeslimZamaniId { get; set; }
        public string TakipNo { get; set; }
        public int Adet { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime GonderimTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Gonderim Gonderim { get; set; }
        public virtual SiparisDetay SiparisDetay { get; set; }
        public virtual TeslimZamani TeslimZamani { get; set; }
    }
}
