//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.IskontoKullanimHareket = new HashSet<IskontoKullanimHareket>();
            this.SiparisDetay = new HashSet<SiparisDetay>();
            this.SiparisHareket = new HashSet<SiparisHareket>();
            this.StokHareket = new HashSet<StokHareket>();
        }
    
        public int SiparisId { get; set; }
        public System.Guid KullaniciId { get; set; }
        public int FaturaAdresId { get; set; }
        public int GonderimAdresId { get; set; }
        public int SiparisOdemeTipId { get; set; }
        public int SiparisDurumTipId { get; set; }
        public int OdemeDurumTipId { get; set; }
        public Nullable<int> KrediKartiTipId { get; set; }
        public Nullable<int> KrediKartiBankaId { get; set; }
        public string KrediKartiAdSoyad { get; set; }
        public string KrediKartiMaskeliNumara { get; set; }
        public Nullable<int> KrediKartiTaksit { get; set; }
        public string KrediKartiTransferId { get; set; }
        public decimal ToplamIskonto { get; set; }
        public decimal ToplamKomisyon { get; set; }
        public decimal KullanilanParaPuanMiktar { get; set; }
        public decimal KalanParaPuanMiktar { get; set; }
        public decimal KuponMiktar { get; set; }
        public decimal UrunKdvDahilToplamTutar { get; set; }
        public decimal UrunKdvHaricToplamTutar { get; set; }
        public decimal UrunKdvToplamTutar { get; set; }
        public decimal OdemeTipUcreti { get; set; }
        public decimal GonderimUcreti { get; set; }
        public decimal OdenecekTutar { get; set; }
        public decimal IadeToplam { get; set; }
        public string Aciklama { get; set; }
        public string KullaniciIp { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public System.DateTime SonIslemTarihi { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Banka Banka { get; set; }
        public virtual KrediKartiTip KrediKartiTip { get; set; }
        public virtual Adres Adres { get; set; }
        public virtual Adres Adres1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IskontoKullanimHareket> IskontoKullanimHareket { get; set; }
        public virtual OdemeDurumTip OdemeDurumTip { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual SiparisDurumTip SiparisDurumTip { get; set; }
        public virtual SiparisOdemeTip SiparisOdemeTip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisHareket> SiparisHareket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokHareket> StokHareket { get; set; }
    }
}
