//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsKuyrugu
    {
        public int SmsKuyruguId { get; set; }
        public string TelefonNo { get; set; }
        public string Icerik { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public int GonderimDenemesi { get; set; }
        public Nullable<System.DateTime> GonderimTarihi { get; set; }
    }
}
