//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareket
    {
        public int StokHareketId { get; set; }
        public int UrunId { get; set; }
        public int StokHareketTipId { get; set; }
        public Nullable<int> SiparisId { get; set; }
        public int OlcuId { get; set; }
        public Nullable<int> IadeTalepId { get; set; }
        public decimal Miktar { get; set; }
        public decimal Fiyat { get; set; }
        public string Aciklama { get; set; }
        public System.Guid KayitKullaniciKey { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Siparis Siparis { get; set; }
        public virtual StokHareketTip StokHareketTip { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
