//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunYorum
    {
        public int UrunYorumId { get; set; }
        public System.Guid KullaniciId { get; set; }
        public int UrunId { get; set; }
        public string Yorum { get; set; }
        public int Puan { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool GosterilsinMi { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Urun Urun { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
