//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunResim
    {
        public int UrunResimId { get; set; }
        public int UrunId { get; set; }
        public int UrunResimTipId { get; set; }
        public string ResimYolu { get; set; }
        public string Aciklama { get; set; }
        public string AltAttribute { get; set; }
        public string TitleAttribute { get; set; }
        public bool YeniMi { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<int> Sira { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Urun Urun { get; set; }
        public virtual UrunResimTip UrunResimTip { get; set; }
    }
}
